import Hero from "./Hero"
import About from "./About"
import Speakers from "./Speakers"
import Schedule from "./Schedule"
import Sponsors from "./Sponsors"
import Features from "./Features"
import Tickets from "./Tickets"
import Testimonials from "./Testimonials"
import Gallery from "./Gallery"
import Info from "./Info"
import FAQ from "./FAQ"
export {Hero,About,Speakers,Schedule,Sponsors,Features,Tickets,Testimonials,Gallery,Info,FAQ}